# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-09-25 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0002_timeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='description',
            field=models.CharField(default='ergergergegre', max_length=200),
            preserve_default=False,
        ),
    ]
